export const RACE_CONFIG = {
  currentCountry: 'USA',
  linkPrefixs: {
    USA: '/event-detail/',
    Canada: '/ca/event-detail/',
    'United Kingdom': '/uk/event-detail/',
    Germany: '/de/event-detail/',
    Sweden: '/se/event-detail/',
    Australia: '/au/event-detail/',
    Mexico: '/mx/event-detail/',
    'South Africa': '/za/event-detail/',
    Spain: '/es/event-detail/',
  },
  eventCountry: {
    wattenmeer: '/de',
    glenworth: '/au',
    sirromet: '/au',
    whitecliffs: '/uk',
    'lake-malaren': '/se',
    mexico: '/mx',
    madrid: '/es',
    niagara: '/ca',
    ontario_trail: '/ca',
    joburg: '/za',
    capetown: '/za',
  },
  regions: {
    southAfricaEvents: 'SOUTH AFRICA',
    northEastEvents: 'NORTHEAST',
    midWestEvents: 'MIDWEST',
    southEvents: 'SOUTH',
    mountainWestEvents: 'MOUNTAIN WEST',
    westCoastEvents: 'WEST COAST',
    europeEvents: 'EUROPE',
    australiaEvents: 'AUSTRALIA',
    mexicoEvents: 'MEXICO',
    canadaEvents: 'CANADA',
  },
  subregion: {
    USA: '',
    Canada: '',
    'United Kingdom': 'UK',
    Germany: 'DE',
    Sweden: 'SE',
    Australia: 'AU',
    Mexico: 'MX',
    'South Africa': 'ZA',
    Spain: 'ES',
  },
};
